### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Jako** [darkstardigital/phpThumbsUp#13]
Thanks for the great package.

Maybe it is possible to have some predefined settings available.

An example: The following config string in system setting phpthumbsup.configs
gallerythumbs|w=165&h=120&zc=0&far=C:contentthumbs|w=250&h=150&zc=1&far=C

would create images virtually in /phpthumbup/gallerythumbs/path/to/originalimage.jpg or /phpthumbup/contentthumbs/path/to/originalimage.jpg with the settings following in the config string.

With this setting based config the available options could be set to empty and no one could tear down and flood the server creating a lot of thumbnails with different sizes not used on the server.

**Comment by sdwespi** [comment]
Thanks for the suggestion, Jako!

We've been tossing this idea around for a while and we're hoping to implement it in the future. While a setting would probably be the easiest way to implement this, we'd really like to make things a bit more user friendly with a custom manager page, but we'll update this issue when we get something together.
