### ISSUE TITLE
Getting wmi and wmt filters working.

### ISSUE THREAD

**Issue by pdincubus** [darkstardigital/phpThumbsUp#18]
I've added them both to the system settings and can get wmt working but cannot figure out how to make it use a custom ttf font, and wmi doesn't seem to work through phpThumbsUp either.

Am I missing something really obvious here? I'm calling like so:

`[[+image_absolute:phpThumbsUp=`w=900&h=650&zc=1&fltr[]=wmt|text for watermark|12|TR|ffffff|assets/templates/DroidSans.ttf|75|10|0|000000|75|`]]`

**Comment by sdwespi** [comment]
Hey Phil,

You might need an absolute path to that font - have you tried tweaking that at all? Also do those settings work with phpThumbOf? It might be an issue with phpThumb and not phpThumbsUp.

Just as a quick FYI - using phpThumbsUp for watermark images / text through a URL will allow visitors to remove part of the URL and get the image without any watermarks. You may want to use the default settings for this, or try pThumb or phpThumbOf.

Thanks,

-Scott

**Comment by pdincubus** [comment]
Hi Scott,

Thanks for the reply. I had considered the URL issue would probably be an issue. At the moment I can get the WMT working, but neither an /assets/templates/font.ttf or font.ttf or /public_html/assets/templates/font.ttf seem to do the trick. I will install pThumb alongside it and see if I have any luck on that front with WMI or WMT

Thanks again.
Phil
