### ISSUE TITLE
Multiple context 

### ISSUE THREAD

**Issue by em-piguet** [darkstardigital/phpThumbsUp#2]
in my multiple context site, i have found that i should write {base_url}thumbs/ in phpthumbsup.base_url settings.

if someone else confirm i think it's a good idea to explain that point in the docs..

**Comment by sdwespi** [comment]
Thanks for your feedback, em-piguet! We'll double check that on some multiple context sites and add it to the documentation.

-Scott

**Comment by em-piguet** [comment]
to be more precise in my case i use Babel for multilingual and my url are domain.com/fr/ domain.com/en/. applying {base_name} or {base_url} is working.
