### ISSUE TITLE
File size limit?

### ISSUE THREAD

**Issue by shaunmorrison** [darkstardigital/phpThumbsUp#22]
Hello

I'm working on a Photographers site and this package seems perfectly suited for it. Is there a width/height/filesize limit? It seems when I make a width call above 1650 the image fails to generate. e.g. 

```
[[+image:phpThumbsUp=`w=1650`]]
```

will work, but the following won't: 

```
[[+image:phpThumbsUp=`w=1660`]]
```

Many thanks, 
Shaun

**Comment by sdwespi** [comment]
Hey Shaun,

There aren't any arbitrary restrictions on file or image size built in to phpThumbsUp, but there's a chance that the responsive thresholds are restricting your image size based on your device width. Does an image get generated that's smaller than 1660, or do you see something else? Is anything showing up in the error log? What is your phpthumbsup.responsive_threshold setting set to and how wide is the device you're using to view the website?

Thanks!

-Scott

**Comment by shaunmorrison** [comment]
Hi

phpthumbsup.responsive is set to no. 

Unfortunately it appears to be a memory issue – this is from the logs. 

[06-Nov-2013 17:58:00 Europe/London] PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 6400 bytes) in /Users/filepath/public/core/model/phpthumb/phpthumb.functions.php on line 372

When the image goes over a certain amount of total pixels and you make too big-a-call with phpthumbsUp it doesn't like it. I don't suppose there's a good way to get around this?

**Comment by jpdevries** [comment]
Have you tried contacting your host about increasing max memory execution limit?

—

**Comment by shaunmorrison** [comment]
Yes, doh – increased memory_limit in php.ini – if it's set to 64M it runs as expected. Thanks... it's been a long day!
