### ISSUE TITLE
>= php 5.3

### ISSUE THREAD

**Issue by em-piguet** [darkstardigital/phpThumbsUp#7]
there should be a note that this script need php >= 5.3
see http://php.net/manual/fr/function.finfo-open.php

on 5.2.x i get these errors

Warning: finfo_open() expects parameter 1 to be long, string given in /.../web/core/components/phpthumbsup/model/phpthumbsup/phpthumbsup.class.php on line 316

Warning: finfo_file(): supplied argument is not a valid file_info resource in /..../web/core/components/phpthumbsup/model/phpthumbsup/phpthumbsup.class.php on line 317

Warning: finfo_close(): supplied argument is not a valid file_info resource in /.../web/core/components/phpthumbsup/model/phpthumbsup/phpthumbsup.class.php on line 318
ÿØÿàJFIFÿþ;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 75 ÿÛC      $.' ",#(7),01444'9=82<.342ÿÛC   2!!22222222222222222222222222222222222222222222222222ÿÀdd"ÿÄ  ÿÄµ}!1AQa"q2‘¡#B±ÁRÑð$3br‚     %&'()_456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyzƒ„…†‡ˆ‰Š’“”•–—˜™š¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ    ÿÄµw!1AQaq"2B‘¡±Á #3RðbrÑ $4á%ñ&'()_56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz‚ƒ„…†‡ˆ‰Š’“”•–—˜™š¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚâãäåæçèéêòóôõö÷øùúÿÚ?ð (¢˜-%´QRÚÛËwu´^Y\"(îÄàÎ˜¹³¸´ò¾Ñ±y¨<Ä+¹OB3ÔTé¿>j>Ñô[é¤³–…m%6Ç?½ù›?tpG×}kÌ©'t6¬Ä¥¢’Q@Q@RÐQKE»àû£câ}>íÑšÖ+ˆšä_îýÖð[Â°«µølº ß‰ìtÍfÆ[¶N"²” Ÿ»À<äý1ïS7híq­Î»Æ>#ðõï….,ô    íµ    î#vs€ymÀxêµã•õŒ<  àÏ    øKSÖ®4—¹a£í)ÜJªŒî?Äzã½|Í%¬·óIeClÍº8˜ä =³ß3Þ¦Ÿk'r­´•¡E-%QE0Š( Š( º¸Çz„d-ìM£ çëÀñ™¼o£¢ç&åqŠ™|,ô?Å­^;ß†¬‚Y"n{bD?Ð×Ë5í.‰Ñ¯í²®Pº·\®ÿ­^/YaïË¨ÞáEVâ (¢€ )( –”‚3Fµ8Úsœcè(¥Úqœzâ—Ërq°“ô ×_ðºÝn¾#èñÚÞc2±…'žGõÉÜôF?A]/ƒ£Ôöæ-1e[×µäóE·,? Lþ4®ÏCñd¶wÃV0Ü‰÷ÀîâÁ òîÊõ=ÀÉ'¥x­z5·†üLš“[-£BðHÃ,s“œûóûq#ÂŽ±g 7QšÎœyn8µ¹ ï-ºÁ'úúPˆãœ`_ÔCh§223ƒ´àA˜¤ØßÝ>¿¦•0Šx‰Š†ù@<Œ°PK’ qì)AíÆ3MïúRü¾”€š)ŒY`œc•¨#úÔ“ÞµÌŠ]"P3Äj~‚ ýß)üê@-ÊrJ·¿4†D¬ägñ®³À·2Yø¢+‹t ˆ™sœòÈAŽzW)˜°>SŸPj{iq&Õr0yêiKUaÅÙ¦}#â_K&™#ÛÞH¥˜®3ŽkçMVÒ->ñ¡ˆ—R¡8ïPË;“µÔtïP Ë~©¸ksJ•úÅ4KCå±Ÿ”œ¨¢'Q¤+– ´`ƒÏN½*,@W“&ï^1L`ƒî±<÷­‹wsEÅÄPÆ¦5r¨Ì«œ

ps: upgrading to 5.3 solve the problem..

**Comment by patrickmckay** [comment]
Thank your for bringing this to our attention. I have added php 5.3.x as a minimum requirement to the documentation.

**Comment by Majkl578** [comment]
I wonder why you didn't use mime_content_type on 5.2 and lower. It is a predecessor of fileinfo and was used on PHP <5.3. But nevermind, seems to be fixed in master. :)
