### ISSUE TITLE
Consider alternative cache folder

### ISSUE THREAD

**Issue by Mark-H** [darkstardigital/phpThumbsUp#8]
I haven't tried phpThumbsUp yet, but like the idea and was just browsing the docs you guys wrote. One thing I noticed was that the cache folder defaults to core/components/phpthumbsup/cache/.

Now I can be wrong on this and you should definitely not take my worth for it - but I think that may be a problem when users install an update for phpthumbsup. By default (and I'm not sure there's a way to disable that) a copy of the files in the directories installed is taken, and preserved in core/packages for uninstalls or something. With another package that also did this, at some point this was starting to cause problems where the update would simply time out because there were so many files being copied across.. 

Reading your docs reminded me of that as I can imagine the cache to grow quite rapidly on bigger image-heavy sites. Might be worth looking into and considering storing cache files in core/cache/phpthumbsup/ or somewhere else entirely instead.

**Comment by sdwespi** [comment]
Thanks for the insight, Mark. We hadn't thought of that.  We're currently working on an update for phpThumbsUp and we'll explore some different caching options before we do.

-Scott
