### ISSUE TITLE
Thumb gets created but problem with delivery to browser?

### ISSUE THREAD

**Issue by ghost** [darkstardigital/phpThumbsUp#9]
Hi,
i did a basic install of phpthumbsup on a modxcloud, no changes, deinstalled phpthumbof beforehand. 
All seems fine, url is created, the actual thumb is created in the cache and when i download it via ftp i can display it fine.
But in the browser, via the url, i get a broken image icon. browser says image contains errors. 

Response headers like this:
Cache-Control:public
Connection:keep-alive
Content-Disposition:inline; filename=test.jpg
Content-Length:22975 
Content-Transfer-Encoding:binary
Content-Type:image/jpeg
Date:Wed, 24 Jul 2013 18:38:37 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:public
Server:nginx/1.2.4

It's usually me who is doing something wrong, but i wouldn't know what this time.
Thanks for the help.
Marc

**Comment by billschmidt** [comment]
Since you're getting a proper looking response but a broken image, it sounds like there was an error somewhere in processing the thumb. See if you can save the broken image and open it with a text editor, there could be a readable error at the top of the file.

**Comment by ghost** [comment]
Hi Bill, thanks for your answer.
I can't see anything in the file that makes any sense to me in the editor.
The downloaded image displays just fine in the browser.
I put it here in case you might want to take a look at it:
http://www.v02.de/test.02129f4bf80c5575badfbdd3439cf28d.jpg

**Comment by billschmidt** [comment]
Are you using it as an output filter and if so, what does your html output look like? Or if you're using a phpThumbsUp URL as your image source, what is the URL you're requesting?

**Comment by ghost** [comment]
I'm using a URL like so:
example.com/phpthumbsup/w/912/h/684/src/assets/test.jpg

**Comment by ghost** [comment]
I just created a new cloud and installed phpthumbsup there. Nothing else. 
And it is working there like it is supposed to. So i'm guessing something in my setup is interfering with phpthup.
I already deactivated all other plugins, no change.
Will investigate further tomorrow and report back.
Thx.

**Comment by ghost** [comment]
Found it, finally.
I had the package ChromePHP installed, which somehow interfered with phpthumbsup.

Well, whatdoyouknow...

Thanks for the help, case closed.
